import asyncio
import os
import uuid
import json
from pathlib import Path

from playwright.async_api import async_playwright

# Directory where recordings will be stored (relative to the project root)
RECORDINGS_DIR = Path(__file__).resolve().parent / "recordings"
RECORDINGS_DIR.mkdir(parents=True, exist_ok=True)

def _log(msg: str):
    print(f"[record_session] {msg}")

async def record_run(run_id: str, server_url: str = "http://127.0.0.1:3000"):
    """Launch a Chromium instance, click the ingest button, and record the whole UI session.

    Parameters
    ----------
    run_id: str
        Unique identifier for this recording (used in filenames).
    server_url: str
        Base URL of the V3 server UI.
    """
    async with async_playwright() as p:
        # Headful browser so the user can see what is happening (set headless=False for headless)
        browser = await p.chromium.launch(headless=False)
        # Create a context that records video for every page
        context = await browser.new_context(
            record_video_dir=RECORDINGS_DIR,
            record_video_size={"width": 1280, "height": 720},
        )
        page = await context.new_page()
        # Navigate to the mission control UI
        await page.goto(f"{server_url}/ui/mission_control.html")
        _log(f"Navigated to {server_url}/ui/mission_control.html")
        # Click the QLoRA ingest button – the button has id="runIngest" in the UI
        await page.click("#runIngest")
        _log("Clicked the ingest button")
        # Wait for the UI to show a success message (adjust selector if UI changes)
        try:
            await page.wait_for_selector("text=Ingest started", timeout=5 * 60 * 1000)  # 5 min timeout
            _log("Ingest start confirmed by UI")
        except Exception as e:
            _log(f"Ingest did not finish within timeout: {e}")
        # Keep the page open for a bit so the training logs can be observed
        await asyncio.sleep(30)  # give the backend time to produce log output
        # Close the context – this finalises the video file
        await context.close()
        await browser.close()

    # Playwright stores the video in a sub‑folder named "recordings/<run_id>-<timestamp>"
    # Find the most recent .webm file produced
    video_files = sorted(RECORDINGS_DIR.rglob("*.webm"), key=os.path.getmtime, reverse=True)
    if not video_files:
        raise RuntimeError("No video file was generated by Playwright")
    latest_video = video_files[0]
    final_path = RECORDINGS_DIR / f"{run_id}.webm"
    latest_video.rename(final_path)
    # Write a small JSON manifest for downstream consumption
    manifest = {
        "run_id": run_id,
        "video_path": str(final_path),
        "timestamp": int(os.path.getmtime(final_path)),
    }
    (RECORDINGS_DIR / f"{run_id}.json").write_text(json.dumps(manifest, indent=2))
    _log(f"Recording saved to {final_path}")

def main():
    # Generate a UUID for this recording run
    run_id = str(uuid.uuid4())
    # Allow the server URL to be overridden via env var for flexibility
    server_url = os.getenv("NEXEN_SERVER_URL", "http://127.0.0.1:3000")
    asyncio.run(record_run(run_id, server_url))

if __name__ == "__main__":
    main()
