
const $=s=>document.querySelector(s);let rows=[],total=0;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Nexen-Action':'launch',...options.headers}});const x=await r.json();if(!r.ok)throw Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail));return x}
function opt(values,current){return values.map(x=>`<option value="${x}" ${x===current?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}
function render(){const q=$('#search').value.toLowerCase();$('#cards').innerHTML=rows.filter(t=>(t.text+' '+t.next_step).toLowerCase().includes(q)).map(t=>`<article class="card glass ${t.priority==='urgent'&&t.status!=='done'?'urgent':''}" data-id="${t.id}"><div class="row"><div><div class="tag">${esc(t.priority)} · ${esc(t.status).replaceAll('_',' ')} · #${t.id}</div><div class="title">${esc(t.text)}</div></div><div class="due">${t.due_date?'Due '+esc(t.due_date):''}</div></div>${t.next_step?'<p><b>Next human step:</b> '+esc(t.next_step)+'</p>':''}${t.reminder_date?'<p class="muted">Follow up: '+esc(t.reminder_date)+'</p>':''}<details><summary>Update task · record outcome</summary><form class="edit"><div class="grid"><label>Status<select name="status">${opt(['planned','in_progress','blocked','done'],t.status)}</select></label><label>Priority<select name="priority">${opt(['urgent','high','normal','low'],t.priority)}</select></label><label>Due date<input type="date" name="due_date" value="${esc(t.due_date)}"></label><label class="full">Next step you need to take<textarea name="next_step" maxlength="2000">${esc(t.next_step)}</textarea></label><label>Next reminder / follow-up<input type="date" name="reminder_date" value="${esc(t.reminder_date)}"></label><label class="full">Call or follow-up outcome<textarea name="outcome" maxlength="4000" placeholder="Who you contacted, what happened, and the next action."></textarea></label></div><div class="actions"><button class="primary">Save changes</button><button type="button" class="historybtn">View history</button><span class="muted result"></span></div><div class="historybox"></div></form></details></article>`).join('');$('#more').hidden=rows.length>=total;$('#count').textContent=`${rows.length} of ${total} tasks loaded`;}
async function load(more=false){try{$('#error').textContent='';const x=await api('/api/tasks?include_done='+$('#done').checked+'&offset='+(more?rows.length:0));rows=more?rows.concat(x.tasks):x.tasks;total=x.total;$('#stats').textContent=Object.entries(x.counts).map(([s,n])=>n+' '+s.replaceAll('_',' ')).join(' · ')||'No tasks yet';render()}catch(e){$('#error').textContent=e.message}}
$('#cards').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,id=Number(f.closest('article').dataset.id),b=f.querySelector('button'),v=Object.fromEntries(new FormData(f));v.due_date=v.due_date||null;v.reminder_date=v.reminder_date||null;b.disabled=true;try{const x=await api('/api/tasks/'+id,{method:'PATCH',body:JSON.stringify(v)});rows=rows.map(t=>t.id===id?x:t);f.querySelector('.result').textContent='Saved';await load()}catch(err){f.querySelector('.result').textContent=err.message}finally{b.disabled=false}});
$('#cards').addEventListener('click',async e=>{if(!e.target.classList.contains('historybtn'))return;const a=e.target.closest('article'),box=a.querySelector('.historybox');try{const x=await api('/api/tasks/'+a.dataset.id);box.innerHTML=x.history.map(h=>`<div class="history"><b>${esc(h.created_at)}</b> · ${esc(h.old_status)} → ${esc(h.new_status)}<br>${esc(h.outcome)}${h.reminder_date?'<br>Next follow-up: '+esc(h.reminder_date):''}</div>`).join('')||'<p class="muted">No recorded updates yet.</p>'}catch(err){box.textContent=err.message}});
$('#new').onclick=()=>$('#newform').hidden=false;$('#cancel').onclick=()=>$('#newform').hidden=true;$('#newform').onsubmit=async e=>{e.preventDefault();try{await api('/api/tasks',{method:'POST',body:JSON.stringify({text:$('#newtext').value})});$('#newtext').value='';$('#newform').hidden=true;await load()}catch(err){$('#error').textContent=err.message}};$('#done').onchange=()=>load();$('#search').oninput=render;$('#refresh').onclick=()=>load();$('#more').onclick=()=>load(true);load();
