"""The predetermined problem catalog.

Every entry is a problem class that autonomous coding on this PC has actually hit or reliably will,
with its detection signals, plain-language symptoms (used for matching and for the held-out eval),
trigger words that raise risk in a plan, causes, prevention, and one or more playbook variants.
Variants compete: the engine picks by measured success (Thompson sampling), so each workflow improves.

Entries marked evidence="seen" came from a real NEXEN failure; "general" are standard software failures.
Field `ext` on a playbook marks steps that touch the outside world and therefore need the owner gate.
"""


def P(pid, area, title, sev, signals, symptoms, triggers, causes, prevent, steps, verify, rollback=None,
      base=0.1, evidence="seen", ext=False, alt=None):
    variants = [{"id": pid + "-A", "steps": steps, "verify": verify, "rollback": rollback or ["restore the backup or previous version"], "ext": ext}]
    if alt:
        variants.append({"id": pid + "-B", "steps": alt, "verify": verify, "rollback": rollback or ["restore the backup or previous version"], "ext": ext})
    return {"id": pid, "area": area, "title": title, "severity": sev, "signals": signals, "symptoms": symptoms,
            "triggers": triggers, "causes": causes, "prevent": prevent, "playbooks": variants, "base_rate": base, "evidence": evidence}


CATALOG = [
    # ---------------------------------------------------------------- environment and machine
    P("ENV-001", "env", "F: drive failing or very slow", 4,
      [r"F:\\", r"Full Repair Needed", r"0\.35 MB/s", r"ripgrep search timed out", r"timed out.*F:"],
      ["reads on the F drive take minutes", "the search over F: timed out", "Windows says the F drive needs repair"],
      ["F:", "vault", "walk", "scan", "NEXEN_MEMORY", "F drive"],
      ["WD easystore failing: reads at about 0.35 MB/s, last DB pages lost"],
      ["Read the recovered H: copy first", "time-box every F: walk", "never write bulk data to F:"],
      ["Switch the read to the H: recovered copy or the H: source of truth", "Wrap any F: walk in a time budget (8-12 s) and a file cap", "Read control files only (00-Control), never crawl the whole vault", "Queue bulky copies for H: and report the partial result as partial"],
      ["The step finished inside its time budget", "No write landed on F: except SESSION-LOG and Current Decisions appends"],
      ["Abort the F: operation; nothing was modified"], 0.5),
    P("ENV-002", "env", "Wrong Python (Microsoft Store stub)", 3,
      [r"Python was not found", r"python3?\.exe.*Microsoft Store", r"App execution aliases"],
      ["python opens the Microsoft Store", "python was not found", "the system python is a stub"],
      ["python", "pip", "script", "venv"], ["System python on PATH is the Store stub"],
      ["Always call H:\\NEXEN_RUNTIME\\python-recovery\\Scripts\\python.exe by full path"],
      ["Replace the bare python call with the full recovery path", "Set NEXEN_PYTHON for child scripts", "Re-run and check the version prints 3.12"],
      ["python --version prints 3.12.x from the recovery path"], None, 0.3),
    P("ENV-003", "env", "Ollama timeout or hang under load", 4,
      [r"TimeoutError", r"model metadata discovery failed", r"11434", r"CUDA.*hang", r"Ollama.*(timed out|not respond)"],
      ["Ollama does not answer", "MARVIN cannot find a model, the lookup timed out", "the local model call hangs"],
      ["ollama", "model", "local model", "inference", "marvin brain", "gpu"],
      ["Machine loaded by several agents", "CUDA discovery hang on the RTX 2070", "model still loading"],
      ["Probe /api/version with an 8 s timeout, not 2 s", "keep a cached verified model list", "CPU-only fallback for gaming or load"],
      ["GET /api/version with an 8 s timeout and retry twice with backoff", "If it answers, ask for one tiny completion on the verified default model", "If it hangs, fall back to CPU-only 3B or a strong cloud model for this task", "Record the latency in the failure ledger"],
      ["A one-word completion returns inside 60 s", "The chosen model is on the verified list"],
      ["Unload models and fall back to the previous route"], 0.4),
    P("ENV-004", "env", "Known-broken local model selected", 3,
      [r"dolphin3", r"qwen3\.5:2b-q4_K_M", r"no output.*hang", r"trm:7b.*not in registry"],
      ["the model never replies", "the chosen model does not exist in the registry", "a model that hung before was picked again"],
      ["model", "pull", "brain", "route"],
      ["dolphin3:latest and qwen3.5:2b-q4_K_M hang on this box; trm:7b was never pulled"],
      ["Use pick_runnable and the verified list: llama3.2:3b chat, qwen2.5-coder:7b code, fara vision"],
      ["Drop the broken tag from the route", "Use the verified default for the task type", "Add the failure to the failure ledger with the tag"],
      ["Completion returns text from a model on the verified list"], None, 0.15),
    P("ENV-005", "env", "Port or service mismatch (n8n 5678 vs 5680)", 3,
      [r"ECONNREFUSED.*567[08]", r"n8n.*(down|not running)", r"5678", r"5680"],
      ["n8n is not on the port I expected", "connection refused on 5678", "workflow import went to the wrong n8n"],
      ["n8n", "workflow", "import", "5678", "5680"],
      ["Local n8n is not running; staging is on 5680"],
      ["Probe both ports and name which instance the action targets"],
      ["Probe 5678 and 5680 with /healthz", "State which instance a workflow belongs to (local vs staging)", "Run imports only against the instance that answers and is marked staging"],
      ["healthz returns ok on the chosen instance", "The import log names the instance"], None, 0.3),
    P("ENV-006", "env", "Process left running after its launcher died", 3,
      [r"address already in use", r"Only one usage of each socket", r"PermissionError.*being used by another process", r"cannot access the file"],
      ["the port is already taken", "the file is locked by another process", "an old engine is still running"],
      ["restart", "kill", "launcher", "serve", "port", "database file"],
      ["A child interpreter survives its supervisor; command line has a quote before serve"],
      ["Find processes by command-line regex that allows an optional quote", "singleton lease per service"],
      ["List python processes by command line", "Stop only the ones that match this service (regex allows an optional quote)", "Verify the port is free, then start once", "Confirm exactly one listener"],
      ["One listener on the port", "Health endpoint returns ok"], ["Start the previous build"], 0.25),
    P("ENV-007", "env", "Windows newline translation changes file hashes", 2,
      [r"hash mismatch", r"sha256.*mismatch", r"\r\n"],
      ["the checksum does not match after writing the file", "hash mismatch on a text file I just wrote"],
      ["sha256", "hash", "manifest", "write_text"],
      ["Text-mode writes turn LF into CRLF on Windows"], ["Write bytes when a hash must hold", "hash the bytes that were written"],
      ["Write with write_bytes or newline=''", "Hash the file from disk, not the in-memory string", "Re-run verification"], ["Manifest hashes equal the on-disk hashes"], None, 0.2),
    P("ENV-008", "env", "Console encoding error (cp1252)", 2,
      [r"UnicodeEncodeError", r"charmap", r"cp1252"],
      ["UnicodeEncodeError when printing", "weird characters or a crash printing an arrow"],
      ["print", "unicode", "output", "log"],
      ["Windows console default code page"], ["Run python with -X utf8 and PYTHONIOENCODING=utf-8"],
      ["Add -X utf8 to the python command", "Set PYTHONIOENCODING=utf-8", "Re-run"], ["No encoding exception"], None, 0.2),
    P("ENV-009", "env", "PowerShell 5.1 vs 7 syntax and parser traps", 2,
      [r"An empty pipe element is not allowed", r"The token '&&' is not a valid", r"ParserError", r"-ExecutionProfile"],
      ["PowerShell says an empty pipe element is not allowed", "&& is not valid in this PowerShell", "parser error in a one-liner"],
      ["powershell", "pipeline", "one-liner", "&&"],
      ["Pipe after a closing brace; && only exists in 7; mistyped flag"],
      ["Assign loop output to a variable then pipe; use ; or if for 5.1"],
      ["Put the loop result in a variable, then pipe the variable", "Replace && with sequential statements and $LASTEXITCODE checks", "Check each flag spelling against --help"], ["The command parses and exits 0"], None, 0.2),
    P("ENV-010", "env", "Low disk space or write to a forbidden drive", 3,
      [r"No space left", r"disk full", r"not enough space", r"C:\\.*write"],
      ["out of disk space", "I was about to write project files to C:", "F has only 22 GB free"],
      ["download", "model", "render", "cache", "backup", "copy"],
      ["F: about 22 GB free; project writes on C: are not allowed"],
      ["Bulky files go to H:\\NEXEN; check free space before a large write"],
      ["Check free space on the target drive", "Redirect the write to H:\\NEXEN or H:\\NEXEN-ENTERPRISE", "If H: is under 10 GB free, stop and report"], ["Output path is on H: and free space stayed above 10 GB"], None, 0.15),
    P("ENV-011", "env", "Command not found or tool not on PATH (git, node)", 2,
      [r"is not recognized as the name of a cmdlet", r"command not found", r"git.*not recognized"],
      ["git is not recognized", "command not found", "the tool is not on PATH"],
      ["git", "npm", "node", "pip", "ffmpeg"],
      ["No git on PATH on this PC; portable tools live under F:\\Apps and H:\\NEXEN\\tools"],
      ["Resolve tools from known folders, not PATH"],
      ["Search known tool folders (H:\\NEXEN\\tools, F:\\Apps, WinGet packages)", "Use the full path", "If missing, use a no-download alternative before proposing an install"], ["The tool runs with its --version"], None, 0.2),
    P("ENV-012", "env", "Long-running command exceeds the foreground timeout", 2,
      [r"did not complete within", r"moved to the background", r"timeout of \d+ms"],
      ["the command timed out and moved to the background", "this scan takes longer than two minutes"],
      ["scan", "walk", "harvest", "build", "download", "train"],
      ["Slow drives and big trees"], ["Run long work in the background with a monitor and a result file"],
      ["Start the job in the background writing to a result file", "Watch the file for the final marker", "Read the result once"], ["The result file contains the end marker"], None, 0.3),
    # ---------------------------------------------------------------- code defects
    P("COD-001", "code", "Import or module not found", 2,
      [r"ModuleNotFoundError", r"ImportError", r"No module named"],
      ["no module named something", "import error at start"], ["import", "module", "package", "pip"],
      ["Wrong interpreter, missing sys.path, or a package not installed in the venv"],
      ["Use the project python; add the engine folder to sys.path in entry points"],
      ["Print sys.executable and sys.path", "Run with the interpreter that owns the package", "If truly missing, look for a vendored or no-download option before installing"], ["The import succeeds in the same command that failed"], None, 0.2, "general"),
    P("COD-002", "code", "Test failure after a change", 3,
      [r"FAILED \(", r"AssertionError", r"FAIL:", r"tests? failed"],
      ["a test fails after my edit", "AssertionError in the suite", "the update was rolled back because tests failed"],
      ["test", "unittest", "pytest", "refactor", "edit"],
      ["The change broke a contract, or the test assumed something false"],
      ["Run the full suite before and after every edit"],
      ["Read the first failure, not the last", "Decide: code wrong or test wrong, and say why", "Fix the smallest cause", "Add a regression case for the real failure", "Run the whole suite again"],
      ["Full suite passes", "A new regression test covers the cause"], ["Revert the last edit"], 0.35, "general"),
    P("COD-003", "code", "Syntax or indentation error", 2,
      [r"SyntaxError", r"IndentationError", r"TabError", r"was never closed"],
      ["syntax error", "a parenthesis was never closed", "unexpected indent"], ["edit", "script", "one-liner", "heredoc"],
      ["Truncated edit or quoting mix-up in an inline script"], ["Write scripts to files instead of long inline -c strings"],
      ["Write the code to a file", "Run python -m py_compile on it", "Fix the reported line"], ["py_compile exits 0"], None, 0.15, "general"),
    P("COD-004", "code", "Unhandled exception from bad input (None, type, key)", 3,
      [r"TypeError", r"KeyError", r"AttributeError", r"NoneType", r"IndexError"],
      ["TypeError on None", "KeyError for a field that was missing", "AttributeError on a null value"], ["input", "parse", "json", "payload"],
      ["Untrusted or partial input reached code that assumed a shape"], ["Validate at the boundary and test the bad cases"],
      ["Reproduce with the exact input", "Validate shape at the boundary (type, required keys, size caps)", "Return a clear error or a safe default, never a silent pass", "Add the bad input as a test"], ["The bad input now yields the designed result"], None, 0.3, "general"),
    P("COD-005", "code", "Silent failure: exception swallowed or error ignored", 4,
      [r"except Exception:\s*pass", r"except:\s*pass", r"swallow"],
      ["the job reported success but nothing happened", "errors are caught and ignored", "the loop never signals failure"],
      ["try", "except", "retry", "loop", "worker"],
      ["Broad except with pass hides real failures"], ["Catch narrow exceptions, log type, return failure state"],
      ["Find the swallowing handler", "Catch the narrow exception and record its type", "Surface failure in the return value or event log", "Add a test that forces the failure and asserts it is reported"], ["Forced failure is visible in the receipt"], None, 0.3, "general"),
    P("COD-006", "code", "Unbounded loop, retry or recursion", 4,
      [r"RecursionError", r"infinite loop", r"retry.*forever", r"maximum recursion"],
      ["it loops forever", "recursion depth exceeded", "retries never stop"],
      ["loop", "retry", "recursive", "while", "watch"],
      ["No depth cap, no budget, no cycle detection"], ["Depth cap 3, candidate cap, time budget, cycle detection, bounded retries"],
      ["Add a depth, count and time budget", "Detect cycles by fingerprint", "Cap retries (3) with backoff", "Test with a hostile input that would loop"], ["The hostile input terminates inside the budget"], None, 0.2, "general"),
    P("COD-007", "code", "Race or lock: database is locked, WAL, concurrent writers", 3,
      [r"database is locked", r"OperationalError", r"SQLITE_BUSY", r"-wal"],
      ["sqlite says the database is locked", "two workers wrote at the same time"],
      ["sqlite", "database", "ledger", "concurrent", "thread"],
      ["Two writers, no timeout, or a reader holding a transaction"], ["Short transactions, timeout 10 s, read-only URIs for readers, one writer lock"],
      ["Open readers with mode=ro", "Use a timeout and an RLock around writes", "Retry once after a short backoff", "Never copy a live WAL database; use the backup API"], ["Concurrent test passes with no lock errors"], None, 0.2, "general"),
    P("COD-008", "code", "Large file or log blows memory or time", 3,
      [r"MemoryError", r"killed", r"\d{2,3} ?MB.*jsonl", r"too large"],
      ["reading a huge log is slow or runs out of memory", "a 70 MB jsonl file hangs the tool"],
      ["log", "jsonl", "transcript", "read", "parse"],
      ["Whole-file read of multi-hundred-MB session logs"], ["Stream line by line; tail with a byte window"],
      ["Stream the file", "For recent data, seek to a tail window", "Skip bad lines instead of failing", "Cap bytes per call"], ["Peak memory stays small and the call returns in seconds"], None, 0.25, "general"),
    P("COD-009", "code", "Regression: working feature broke after an edit", 4,
      [r"regression", r"used to work", r"worked before"],
      ["it worked yesterday and now it does not", "my change broke an older feature"], ["refactor", "edit", "update", "upgrade"],
      ["No golden case guarding the old behavior"], ["Golden cases for every contract; run before shipping"],
      ["Bisect by reverting the last change", "Write the failing case first", "Fix, then keep the case as a permanent golden test"], ["Golden suite passes"], ["Revert to the last passing version"], 0.3, "general"),
    P("COD-010", "code", "Template-similar items wrongly treated as updates", 3,
      [r"Winner on this input", r"wrongly superseded", r"value_change"],
      ["two different bake-off winners replaced each other", "similar rows overwrote each other in memory"],
      ["supersede", "update", "dedupe", "memory", "ledger"],
      ["Shared template text plus a changed number looked like a value update"], ["Supersede only the same claim with a different value; otherwise keep both"],
      ["Run reaudit_supersessions", "Undo unjustified supersessions", "Check the same-claim rule (non-numeric word overlap >= 0.85)"], ["Both facts are admitted and recallable"], ["nexen learn undo <new id>"], 0.2),
    P("COD-011", "code", "Dependency missing and a download would be needed", 2,
      [r"pyinstaller", r"pip install", r"No matching distribution"],
      ["I need a package that is not installed", "pyinstaller is not available"], ["install", "package", "pip", "exe", "compile"],
      ["Tooling not on the machine; downloads need the owner"], ["Prefer what is already installed"],
      ["Search installed runtimes and venvs first", "Use a no-download alternative (csc.exe for an exe shell, stdlib http.server)", "Only if none exists, queue a download request with name, source and size"], ["The goal is met without a new download"], None, 0.3),
    P("COD-012", "code", "Security finding: injection, secrets, unsafe execution", 5,
      [r"shell=True", r"eval\(", r"os\.system", r"password\s*=", r"SQL injection", r"api[_-]?key"],
      ["a secret is in a log", "command injection risk", "user text reaches a shell"],
      ["secret", "token", "password", "shell", "sql", "exec"],
      ["Credential shapes in chats, LAN addresses, shell=True, string-built SQL"], ["Redact on read; parameterized queries; list-form subprocess; allowlists"],
      ["Remove the secret from files and logs", "Redact on every read path", "Use list-form subprocess and parameterized SQL", "Rotate the credential through the owner"], ["Secret scan finds nothing", "Redaction test passes"], None, 0.2, "general", True),
    P("COD-013", "code", "Slow or hanging network call with no timeout", 3,
      [r"urlopen\(", r"requests\.get\(", r"timed out", r"ReadTimeout"],
      ["the request never returns", "no timeout on an HTTP call"], ["http", "request", "api", "fetch", "urlopen"],
      ["Missing timeout; remote down"], ["Every network call gets a timeout and a failure state"],
      ["Add timeout=8 to the call", "Treat timeout as a state, not a crash", "Retry once with backoff"], ["Call fails fast when the host is blackholed"], None, 0.3, "general"),
    P("COD-014", "code", "Path with spaces, quotes or Windows separators breaks", 2,
      [r"The system cannot find the path", r"FileNotFoundError", r"No such file or directory"],
      ["file not found though it exists", "the path has a space in it", "my regex missed a quote in the command line"],
      ["path", "quote", "user", "command line"],
      ["Unquoted spaces; optional quote before arguments"], ["Use pathlib; quote arguments; allow an optional quote in regexes"],
      ["Print the exact path repr", "Use pathlib.Path and list-form subprocess", "Quote in shell strings"], ["The path resolves and the file opens"], None, 0.25, "general"),
    P("COD-015", "code", "Merge conflict or two sessions editing the same files", 4,
      [r"merge conflict", r"CONFLICT \(content\)", r"another session", r"lease"],
      ["two chats edited the same file", "someone else changed the code I am editing", "git conflict markers in a file"],
      ["parallel", "session", "worktree", "lease", "overlap"],
      ["Several agents run at once on this PC"], ["Read the coding status report and take the lease before writing; one writer per file"],
      ["Read NEXEN-CODING-STATUS-LATEST.txt for active ownership", "Take the lease or choose a disjoint file set", "If the file changed, re-read and merge by hand, then re-test"], ["No file has two writers and the suite passes"], None, 0.3),
    P("COD-016", "code", "Flaky or order-dependent test", 2,
      [r"flaky", r"passes alone but fails", r"intermittent"],
      ["the test passes sometimes", "fails only when run with others"], ["test", "sleep", "thread", "temp"],
      ["Shared state or real clocks and files"], ["Sandbox paths per test; no shared singletons"],
      ["Run the test alone and in the suite", "Find the shared state (singleton, env, path)", "Isolate with temp dirs and reset hooks"], ["Ten repeated runs all pass"], None, 0.2, "general"),
    P("COD-017", "code", "Performance regression or slow path", 3,
      [r"slow", r"took \d{2,} ?s", r"elapsed: \d{2,}s"],
      ["this got much slower", "the harvest takes 100 seconds"], ["scan", "index", "walk", "query"],
      ["Unbounded walk, no index, repeated work"], ["Time budget, caching by hash, indexes"],
      ["Measure which stage is slow", "Cache by file hash and mtime", "Add an index or narrow the scan", "Re-measure"], ["Measured time dropped and results are identical"], None, 0.3, "general"),
    # ---------------------------------------------------------------- models and agents
    P("MOD-001", "model", "Model claims success without a receipt", 5,
      [r"Not verified yet", r"unsupported claim", r"no receipt", r"fake success"],
      ["the model said it posted but there is no proof", "MARVIN claimed an action ran with no receipt", "old handlers report fake success"],
      ["claim", "done", "posted", "sent", "scheduled", "published"],
      ["Local models narrate actions they cannot take"], ["Guard replies; require a file path, hash, screenshot or provider receipt"],
      ["Strip the claim", "Ask for the receipt (path, hash, screenshot, execution id)", "Label the status prepared or unverified until a receipt exists"], ["Every done-claim cites a receipt"], None, 0.4),
    P("MOD-002", "model", "Invalid JSON or tool call from a model", 3,
      [r"JSONDecodeError", r"Expecting value", r"invalid tool call", r"schema"],
      ["the model returned broken JSON", "the tool call has the wrong arguments"], ["json", "tool", "schema", "function calling"],
      ["Small quantized models drift from schemas"], ["Constrain output; validate; repair once; fall back to a stronger model"],
      ["Validate against the schema", "Repair by extracting the first {...} block", "If still invalid, retry once with the schema in the prompt", "Escalate to a stronger model"], ["Output validates against the schema"], None, 0.35),
    P("MOD-003", "model", "Context window overflow", 3,
      [r"context length", r"maximum context", r"too many tokens", r"num_ctx"],
      ["the prompt is too long", "context exceeded"], ["prompt", "context", "long", "transcript"],
      ["8192-token CPU fallback; long agent prompts"], ["Chunk, retrieve, summarize; keep prompts small"],
      ["Retrieve only the top passages", "Summarize old turns", "Use a larger-context model for this one task"], ["Prompt fits and answer cites the retrieved passages"], None, 0.3),
    P("MOD-004", "model", "Rate limit or quota exhausted on a provider", 4,
      [r"429", r"rate limit", r"quota", r"usage limit", r"insufficient_quota"],
      ["HTTP 429", "I hit my usage limit", "the provider says quota exceeded"], ["api", "provider", "claude", "codex", "gemini", "openai"],
      ["Subscriptions have caps; a stale key can 429 without fallback"], ["Checkpoint before the cap; route to the next provider; local fallback last"],
      ["Write a checkpoint (patch, tests, next step) to the vault", "Switch to the next provider in the route (Claude, Codex, Antigravity, then local 7B)", "Back off and retry the primary after reset"], ["Work resumed on another provider with the checkpoint"], None, 0.4),
    P("MOD-005", "model", "Provider authentication rejected (401)", 3,
      [r"401", r"Authentication required", r"rejected your API key", r"Unauthorized"],
      ["Hermes says LM Studio rejected the key", "401 from the provider"], ["hermes", "lm studio", "key", "auth", "login"],
      ["Expired or wrong key in a provider profile"], ["Keep keys in Credential Manager; test each route with a one-word prompt"],
      ["Run a one-word prompt on the route", "If 401, switch to a route that passes (freellmapi/auto)", "Queue 'update the key' for the owner; never type or store the key"], ["A one-word prompt returns OK on the chosen route"], None, 0.35, "seen", True),
    P("MOD-006", "model", "V3 hub locked or same-origin guard rejects a local call", 3,
      [r"Unlock NEXEN first", r"Local writes require the same-origin", r"401.*login", r"403.*PC control"],
      ["the NEXEN hub says unlock first", "writes need the same-origin page"], ["marvin chat", "v3", "hub", "8788", "api/marvin"],
      ["V3 asks for the owner password"], ["Send the same-origin Origin and action headers; never type the unlock password"],
      ["Send Origin and X-Nexen-Action as the V3 pages do", "If 401, do not log in; use MARVIN's local brain module", "Tell the owner to unlock once if the hub path is needed"], ["Reply returns via the local brain or the hub"], None, 0.3, "seen", True),
    P("MOD-007", "model", "Tuned model worse than the base (eval gate fails)", 4,
      [r"gate failed", r"did not beat", r"eval.*worse", r"regressed"],
      ["the fine-tuned model scores lower than the base", "the eval gate rejected the tune"], ["finetune", "tuned", "eval", "lora"],
      ["Noisy data, leakage, over-training, bad template"], ["A tuned model ships only if it beats the base on the held-out eval"],
      ["Do not ship", "Inspect the lowest-scoring categories", "Remove noisy sources (separate tags make this easy)", "Retrain smaller or fewer epochs", "Re-run the gate"], ["Tuned beats base on the held-out set and on the policy bank"], ["Keep serving the base"], 0.35),
    P("MOD-008", "model", "Fine-tune out of memory on the RTX 2070", 3,
      [r"CUDA out of memory", r"OutOfMemoryError", r"OOM"],
      ["training crashed out of memory", "8 GB is not enough"], ["train", "qlora", "8b", "finetune"],
      ["8B QLoRA needs 10-12 GB"], ["Train 4B locally; run 8B on a free Kaggle T4 x2"],
      ["Retry with a smaller batch and sequence length", "Fall back to the 4B base", "Use the free Kaggle script for 8B, then merge and quantize at home"], ["Training completes and the adapter merges"], None, 0.4),
    P("MOD-009", "model", "Hallucinated source or statistic", 4,
      [r"hallucinat", r"made up", r"no such (paper|source)", r"cannot be verified"],
      ["the answer cites something that does not exist", "an invented statistic"], ["research", "cite", "statistic", "study"],
      ["Model completes plausible text"], ["Require a source id; trust scores by source class; chat claims stay low trust"],
      ["Ask for the source id", "Fetch or open the source", "Admit to memory only with a source and mark chat-only claims as low trust"], ["Each retained claim has a source id"], None, 0.35),
    P("MOD-010", "model", "Retrieval miss: paraphrase shares no words", 2,
      [r"recall returned nothing", r"no matching notes", r"lexical retrieval overlap only"],
      ["search finds nothing though the note exists", "different wording, same meaning"], ["recall", "search", "retrieval", "embedding"],
      ["Lexical similarity only"], ["Query expansion; optional embedding function"],
      ["Rewrite the query with synonyms and key terms", "Try the embedding route when available", "Report low retrieval confidence honestly"], ["The expected note appears in the top five"], None, 0.3),
    # ---------------------------------------------------------------- infrastructure and workflow
    P("INF-001", "infra", "Global STOP or PAUSE is active", 5,
      [r"STOP", r"PAUSE_AUTONOMY", r"loop\\STOP", r"autonomous work is paused"],
      ["the STOP file is present", "autonomous work is paused", "owner stop flag is on"], ["autonomous", "loop", "swarm", "24/7", "start", "dispatch"],
      ["Owner set a global stop"], ["Only the owner lifts STOP; internal prep and on-demand actions continue"],
      ["Do not start autonomous loops or swarm jobs", "Continue read-only, prep and tests the owner asked for", "List what is waiting so the owner can lift STOP knowingly"], ["No autonomous process started while STOP existed"], None, 0.9),
    P("INF-002", "infra", "n8n workflows are drafts, NoOp or have no credentials", 3,
      [r"NoOp", r"0 credentials", r"credentials? not (set|found)", r"workflow.*(draft|inactive)"],
      ["the workflow imported but does nothing", "no credentials are saved in n8n", "all workflows are inactive"], ["n8n", "workflow", "credential", "oauth", "publish"],
      ["Exports are drafts; OAuth needs the owner"], ["Never call a workflow done without an execution id and output"],
      ["Run with labeled test input and record execution id and output", "List nodes that are NoOp or lack credentials", "Queue the OAuth steps for the owner"], ["Execution id exists and its output was inspected"], None, 0.5, "seen", True),
    P("INF-003", "infra", "Swarm or worker job without a real handler", 4,
      [r"192 queued", r"fake success", r"no handler", r"ticket 229"],
      ["queued jobs report success but did nothing", "old handlers return fake success"], ["swarm", "worker", "jobs", "queue", "handler"],
      ["Handlers were stubs"], ["Unlock only after one real handler passes with an inspected receipt (ticket 229)"],
      ["Do not run the queue", "Build one real handler and canary it with a receipt", "Inspect the receipt by hand", "Then widen"], ["Canary receipt inspected"], None, 0.6),
    P("INF-004", "infra", "PC2 offline or only the share is reachable", 3,
      [r"PC2", r"PC2-HOST", r"pending_owner_launch", r"SMB"],
      ["PC2 is not responding", "the worker on PC2 was never launched"], ["pc2", "remote", "worker", "pair"],
      ["Node visibility is not worker readiness"], ["Track node availability and worker success separately; pull-based job queue"],
      ["Check the share and the PAIR node separately", "Write a job; wait for a result with the same hash", "Mark PC2 execution proven only after a verified round trip", "Never put connection details in files"], ["Round-trip receipt with matching hashes"], None, 0.4),
    P("INF-005", "infra", "Another process or agent owns the lease", 3,
      [r"lease", r"ownership", r"already owned"],
      ["the implementation lease is taken", "another agent holds the task"], ["task", "ticket", "lease", "owner"],
      ["Parallel agents"], ["Check the coding status report first"],
      ["Read the latest coding status report", "Choose a disjoint packet or wait", "Record the lease in the session log"], ["No two writers on one file or task"], None, 0.3),
    P("INF-006", "infra", "Service or scheduled task silently stopped", 3,
      [r"stale", r"missed report", r"no heartbeat", r"stopped at"],
      ["the daily report did not arrive", "the six-hour pulses stopped", "a worker has no recent heartbeat"], ["scheduler", "heartbeat", "cron", "daily", "boot"],
      ["No watchdog on the watcher"], ["Heartbeat files with age checks"],
      ["Check the heartbeat age against its interval", "Restart the service once through its launcher", "Write the incident to the failure ledger"], ["A fresh heartbeat within one interval"], None, 0.3),
    P("INF-007", "infra", "Continuous-learning watcher watches the wrong folder and ingests nothing", 3,
      [r"Marvin_Brain_Index", r"continuous_learning_watcher", r"knowledge_chunks"],
      ["the learning pipeline started but the index is empty", "the watcher logs started and never ingests"], ["watcher", "learning", "index", "ingest"],
      ["Watches H:\\NEXEN\\obsidian-vault; the live vault is F:\\NEXEN_MEMORY"], ["V4's loop reads sources directly"],
      ["Point V4's harvest at the live sources", "Leave the old watcher untouched", "Verify the ledger count rises"], ["Ledger item count increased from real sources"], None, 0.5),
    # ---------------------------------------------------------------- money, policy and external effects (owner gates)
    P("POL-001", "policy", "Action would spend money", 5,
      [r"purchase", r"subscribe", r"top.?up", r"paid ads?", r"upgrade plan", r"credits?"],
      ["this needs a paid plan", "it would charge a card", "buy credits"], ["buy", "pay", "spend", "subscribe", "upgrade", "ads", "credits", "renew"],
      ["Paid usage requires a MARVIN approval"], ["Queue amount, purpose, provider and scope; continue independent work"],
      ["Do not spend", "Write the approval request: amount or cap, purpose, provider, scope", "Continue with free alternatives"], ["Approval queue shows the exact request"], None, 0.5, "seen", True),
    P("POL-002", "policy", "Action would publish, post or message a person", 5,
      [r"publish", r"post to", r"send (an )?email", r"dm ", r"schedule.*post"],
      ["post this video", "send the reply to the client", "schedule the upload"], ["publish", "post", "send", "dm", "email", "upload", "schedule"],
      ["Public and outbound actions need the owner and a native receipt"], ["Draft only; exact-action approval; readback after"],
      ["Prepare the draft and stop", "Queue an exact-action approval", "After approval, act and read the provider receipt back"], ["Native provider receipt and readback exist"], None, 0.6, "seen", True),
    P("POL-003", "policy", "Credentials, CAPTCHA, KYC or account creation needed", 5,
      [r"captcha", r"sign in", r"password", r"KYC", r"verify your identity", r"MFA"],
      ["it needs a login", "there is a captcha", "it asks to verify identity"], ["login", "account", "captcha", "kyc", "oauth", "signup"],
      ["Only the owner enters credentials and passes bot checks"], ["Prepare everything up to the gate; hand the owner one clear step"],
      ["Stop at the gate", "State the single human step", "Resume after the owner finishes"], ["Owner completed the step"], None, 0.7, "seen", True),
    P("POL-004", "policy", "Clipping without a paid campaign", 4,
      [r"clip", r"whop", r"campaign"], ["clip this video", "start the autoclipper"], ["clip", "clipper", "autoclip", "shorts", "reels"],
      ["Clips only for an active paid campaign or labeled research"], ["Research clips go to a do-not-post folder"],
      ["Check for an active paid campaign", "If none, label the run research and write to the research folder", "Never post research clips"], ["Output is in the research folder or tied to a paid campaign id"], None, 0.4),
    P("POL-005", "policy", "Rejected creative reused", 3,
      [r"rejected", r"owner quality rejection", r"creative_approval=false"],
      ["reuse the cards the owner rejected", "recycle P02 to P07"], ["recycle", "reuse", "tiktok", "cards", "creative"],
      ["Owner rejected specific artifacts"], ["Record every rejection; never silently recycle"],
      ["Check the feedback ledger for the artifact", "If rejected, rework from scratch or drop", "Record the new attempt as separate"], ["No rejected artifact reused"], None, 0.3),
    P("POL-006", "policy", "Untrusted download or execution", 4,
      [r"download", r"curl .*\| *sh", r"\.exe", r"unknown source"],
      ["download this installer", "run a script from the internet"], ["download", "install", "exe", "script", "repo"],
      ["Downloads and execution need the owner when the source is untrusted"], ["State filename, source and size; scan first; prefer installed tools"],
      ["Name the file, source and size", "Check license and hash", "Wait for the owner", "Never execute before a scan"], ["Owner approved the exact file"], None, 0.3, "general", True),
    P("POL-007", "policy", "Private data would leave the PC", 5,
      [r"upload", r"cloud", r"send to", r"PC2.*address", r"192\.168"],
      ["send my private chats to a cloud model", "put the PC2 address in a file"], ["upload", "cloud", "share", "export", "private"],
      ["Archive and personal data stay local; PC2 details stay private"], ["Redact; send only bounded relevant slices"],
      ["Redact credential shapes and LAN addresses", "Send the smallest slice that answers the question", "Log what left the machine"], ["Nothing sensitive in the outbound payload"], None, 0.3, "seen", True),
    # ---------------------------------------------------------------- learning and data
    P("LRN-001", "learning", "Duplicate or near-duplicate knowledge floods memory", 2,
      [r"duplicate", r"near duplicate", r"REINFORCE"],
      ["the same note is stored many times", "memory is full of repeats"], ["ingest", "harvest", "dedupe", "memory"],
      ["No novelty gate"], ["Novelty gate with dup threshold 0.90"],
      ["Run through the novelty gate", "Merge sources into the existing item", "Raise trust only for independent sources"], ["Item count grows only on novel facts"], None, 0.3),
    P("LRN-002", "learning", "Conflicting facts (old number vs new number)", 3,
      [r"contradict", r"conflict", r"value_change", r"stale"],
      ["two notes disagree about a count", "the old status is stale"], ["status", "count", "number", "state"],
      ["Notes written at different times"], ["Bitemporal validity; newer and equally trusted wins; otherwise hold"],
      ["Compare observed_at and trust", "Supersede with a validity window when newer and as trusted", "Hold a conflict where trust gap is small and ask for a receipt"], ["Recall as-of returns the right belief for each date"], ["nexen learn undo"], 0.35),
    P("LRN-003", "learning", "Chat-only claim treated as fact", 3,
      [r"chat:", r"user-reported", r"assistant claim"],
      ["an assistant said it was done", "only a chat message supports this"], ["claim", "reported", "said"],
      ["Archived assistant claims are not execution evidence"], ["Source class trust: chat 0.35 until corroborated"],
      ["Mark as unverified", "Look for a receipt or a second independent source", "Reinforce when found"], ["Trust rose only after corroboration"], None, 0.4),
    P("LRN-004", "learning", "Dataset leakage or low-quality training rows", 3,
      [r"leak", r"duplicate rows", r"dropped", r"no_pair"],
      ["eval rows also appear in train", "training data has secrets or repeats"], ["dataset", "train", "eval", "split"],
      ["Splits by row instead of by session"], ["Split by whole session or file; scrub secrets; dedupe"],
      ["Split by session", "Scrub and rescan", "Keep separate source tags so noisy sources can be dropped"], ["Rescan finds zero secrets and zero overlap"], None, 0.3),
    P("LRN-005", "learning", "Self-tuning drifts the gate", 3,
      [r"param_history", r"self-tune", r"drift"],
      ["thresholds changed and quality dropped", "the tuner made things worse"], ["tune", "threshold", "parameter"],
      ["Over-fitting to few labels"], ["Bounds, golden wall, min labels 12, logged and reversible"],
      ["Roll back with nexen learn rollback", "Add the failing case to the golden set", "Require more labels before tuning again"], ["Golden cases pass with restored parameters"], ["nexen learn rollback"], 0.15),
    P("NAM-001", "learning", "Name confusion: JARVIS and MARVIN treated as two assistants", 4,
      [r"(?i)\bjarvis\b.*\bmarvin\b", r"(?i)\bmarvin\b.*\bjarvis\b", r"(?i)which one is jarvis", r"(?i)jarvis_runtime", r"(?i)/jarvis\b"],
      ["is JARVIS a different assistant from MARVIN", "old notes say JARVIS but the assistant is MARVIN", "a file or route still says jarvis"],
      ["jarvis", "marvin", "assistant name", "rename"],
      ["The assistant was named JARVIS first; older code, notes, chats and datasets still use that name"],
      ["identity.py hard-codes JARVIS = MARVIN; normalize every text V4 stores or prompts; keep legacy file, route and key names working"],
      ["State plainly: JARVIS is MARVIN, the one NEXEN assistant", "Rewrite prose and comments to MARVIN (AST-verified); keep legacy identifiers such as jarvis_runtime.py and /jarvis working through the alias map",
       "Never rename third-party project names (OpenJarvis, isair/jarvis); they are proper nouns with licenses", "Record any new legacy identifier in LEGACY-IDENTIFIERS.md"],
      ["identity.normalize returns MARVIN for the old name and leaves protected names alone", "agent_key('jarvis') == 'marvin'"], None, 0.2),
    # ---------------------------------------------------------------- boot and runtime failures read from NEXEN and MARVIN logs (2026-10-06)
    P("OPS-001", "ops", "Launch command splits a path that contains a space", 3,
      [r"Cannot find module 'C:\\Users\\exampleuser'", r"can't open file 'C:\\+Users\\+exampleuser'", r"MODULE_NOT_FOUND", r"python\.exe.*can't open file"],
      ["n8n boot cannot find module C:\\Users\\exampleuser", "python cannot open file C:\\Users\\exampleuser", "a hook or boot script died because the profile folder has a space"],
      ["boot", "launch", "start process", "hook", "scheduled task", "user", "node", "arguments"],
      ["The profile folder is 'user'; an unquoted argument splits at the space (seen in n8n-5680-boot.stderr.log and in a plugin hook)"],
      ["Pass arguments as a list, or wrap every path in quotes; preflight scans launch commands for unquoted spaced paths"],
      ["Find the launch command that holds the path", "Rewrite it with list-form arguments or quotes around each path", "Run it once and read stderr", "Add the command to the preflight scan"],
      ["The process starts with the full path in its command line", "stderr stays empty for 30 s"], ["Restore the previous launch script"], 0.45),
    P("OPS-002", "ops", "Boot reports a service down seconds after starting it", 2,
      [r"BOOT REPORT", r"BOOT REPORT .*=False", r"\d{4}=(True|False)", r"start cmd fired", r"already up - skip.*=False"],
      ["the boot report says n8n is False right after it started n8n", "boot says the hub is up and then says it is down", "the report was written before the service finished loading"],
      ["boot", "report", "healthz", "n8n", "hub", "start"],
      ["Health is read once about 20 s after the start command; n8n needs longer, and the hub answered late"],
      ["Poll health with backoff up to 90 s; report starting, up or down, never a single snapshot"],
      ["Poll /healthz every 5 s for up to 90 s", "Report 'starting' until the deadline, then 'down' with the last error", "Write the final state with its timestamp"],
      ["Boot report matches a health probe taken 2 minutes later"], None, 0.4),
    P("OPS-003", "ops", "Boot logs 'started' for a worker that died on its first line", 4,
      [r"UnicodeEncodeError.*charmap", r"ModuleNotFoundError: No module named 'requests'", r"-boot\.stderr\.log", r"marvin_swarm_(worker|orchestrator)"],
      ["the swarm worker says started but its stderr holds a traceback", "the orchestrator died on import requests under the wrong python", "an emoji print killed a background worker"],
      ["swarm", "worker", "orchestrator", "boot", "background", "emoji", "print", "python"],
      ["Workers launch under the system Python 3.12 (no requests) instead of the recovery python; stdout is cp1252 so an emoji print raises"],
      ["Launch with the recovery python and -X utf8; keep emoji out of print; after launch confirm the PID is alive and stderr is empty"],
      ["Read the newest *-boot.stderr.log for the final exception line", "Relaunch with H:\\NEXEN_RUNTIME\\python-recovery\\Scripts\\python.exe -X utf8", "Confirm the PID after 10 s and a heartbeat after one interval", "Only then write 'started' to boot.log"],
      ["A live PID and a fresh heartbeat", "stderr log has zero bytes after the restart"], ["Stop the new process; the old state was already stopped"], 0.5),
    P("OPS-004", "ops", "Service data folder points at a drive that is missing or failing", 3,
      [r"ENOENT.*mkdir.*F:\\", r"mkdir 'F:\\NEXEN_GAME", r"no such file or directory.*\.n8n"],
      ["n8n cannot create its settings folder on F:", "a service starts with its data directory on the failing drive"],
      ["n8n", "user folder", "data folder", "F:", "settings", "start"],
      ["N8N_USER_FOLDER pointed at F:\\NEXEN_GAME\\...\\data\\n8n which no longer mounts"],
      ["Keep every service data folder on H:; preflight checks the folder exists before the service starts"],
      ["Set the data folder to an H: path", "Copy the old folder from the recovered H: copy if one exists", "Start once and confirm the settings file is written", "Remove the F: path from the launcher"],
      ["The service writes its settings file under H:", "No process holds an F: path"], ["Point back to the previous folder"], 0.3),
    P("OPS-005", "ops", "MARVIN action has no handler", 3,
      [r"handler \w+ missing", r"handler.*missing", r"no handler for action", r"unknown action"],
      ["marvin.show-work failed with handler showWork missing", "a button is listed but does nothing", "an action exists in the catalog with no code behind it"],
      ["action", "marvin", "button", "handler", "show-work", "bus"],
      ["The action catalog lists show-work but the dispatcher has no showWork function; 11 failed events in events.jsonl"],
      ["At start, compare every action id to a handler and hide or flag the ones without one"],
      ["List catalog action ids and dispatcher handlers", "Mark each action without a handler as unavailable in the UI", "Write the handler or remove the action", "Re-run the action once and read the event status"],
      ["Every listed action returns done or an honest denied", "Zero 'handler missing' events in the next 24 h"], ["Remove the action from the catalog"], 0.5),
    P("OPS-006", "ops", "Bus action fails with a cut traceback or a bare deadline message", 3,
      [r"CalledProcessError", r"reached its deadline", r"inspect its local receipt", r"subprocess\.py.*line \d+, in run"],
      ["whop.campaigns failed and only the subprocess line shows", "the daily content worker failed or reached its deadline with no reason", "the failure text does not say which step broke"],
      ["whop", "campaigns", "content.daily", "subprocess", "deadline", "worker", "bus"],
      ["The runner stores the first 300 characters of the error, which are the call stack's top frames; the child's stderr tail is not kept"],
      ["Store the last 20 stderr lines of every child, the exit code and the elapsed seconds; separate deadline from crash"],
      ["Capture stderr and the exit code of the child", "Save the stderr tail in the event summary", "Label the event deadline or crash", "Retry a deadline once with a longer budget; do not retry a crash"],
      ["The event summary names the failing step and exit code"], None, 0.4),
    P("OPS-007", "ops", "Heartbeat or sync logs success without measuring anything", 3,
      [r"Routine: Obsidian Vault sync complete", r"Hardware Engine \(Ports \d+-\d+\) status check", r"Cycle complete\. Awaiting next event"],
      ["the autonomy log says vault sync complete every minute in two milliseconds", "a status check line that prints no result", "the log looks healthy but shows no counts"],
      ["heartbeat", "sync", "autonomy", "status check", "complete", "log"],
      ["nexen_24_7_autonomy.log repeats three fixed lines per minute; none carries a count, port result or byte size (suspected placeholder, not yet confirmed in code)"],
      ["A success line must carry a measured value: ports probed and their answers, files synced and bytes; no value means unverified"],
      ["Open the routine's code and find what 'complete' checks", "Add counts: ports answered out of 4, files copied, elapsed ms", "Mark any routine with no measurement as unverified", "Alert when the same line repeats with no count for 10 cycles"],
      ["Each success line carries a number and the number moves with real work"], None, 0.35),
    P("OPS-008", "ops", "Tracker or controller heartbeat stale with its process gone", 4,
      [r"heartbeat is stale", r"PID \d+ is absent", r"TRACKER-pc1\.json remains", r"Tracker publication remains stale", r"\.tmp .* while canonical"],
      ["the task142 controller heartbeat is stale and its PID is absent", "TRACKER json is older than the database it describes", "a .tmp file was left behind by a crash"],
      ["tracker", "controller", "lease", "heartbeat", "task142", "pid", "tmp"],
      ["Writer crashed between writing .tmp and renaming it; lease holds a dead PID so no one restarts it"],
      ["Atomic write with cleanup; lease records PID and start time and counts as dead when the PID is gone"],
      ["Check the PID in the lease with a process lookup", "If absent and the lease is older than two intervals, mark it dead", "Delete the stale .tmp after copying it aside", "Restart through the launcher once and confirm a fresh heartbeat"],
      ["Tracker mtime is newer than the last database change", "One live PID holds the lease"], ["Restore the copied .tmp"], 0.4),
    P("OPS-009", "ops", "Log file grows without a limit", 2,
      [r"uncensored_agent\.log", r"n8n-5680\.stdout\.log", r"disk.*full", r"log.*too large"],
      ["one log is 7 MB and still growing", "grep over the log folder takes minutes", "the log has millions of repeated lines"],
      ["log", "logging", "agent", "stdout", "rotate", "size"],
      ["No rotation: uncensored_agent.log is 7.1 MB, n8n-5680.stdout.log is 0.9 MB; slow F: and H: reads make large logs costly"],
      ["RotatingFileHandler at 2 MB with 3 backups; repeated identical lines collapse into one with a count"],
      ["Switch the logger to RotatingFileHandler(maxBytes=2 MB, backupCount=3)", "Collapse repeats into 'last line x N'", "Archive the old log to H:\\NEXEN\\logs\\archive"],
      ["Log size stays under 2 MB per file"], None, 0.3),
    P("OPS-010", "ops", "Vendor telemetry error read as a real failure", 1,
      [r"\[Rudder\] error", r"Response error code: ECONNRESET", r"DEP0060", r"DeprecationWarning"],
      ["n8n logs a Rudder ECONNRESET error", "a deprecation warning counted as a failure"],
      ["n8n", "telemetry", "rudder", "deprecation", "warning"],
      ["n8n tries to send usage telemetry and the connection resets; the deprecation warning comes from a dependency"],
      ["Set N8N_DIAGNOSTICS_ENABLED=false; the failure miner ignores these signatures"],
      ["Confirm the error names telemetry or a deprecation", "Set N8N_DIAGNOSTICS_ENABLED=false in the launcher", "Do not open a repair task"],
      ["The line no longer appears after the next start"], None, 0.1),
    # ---------------------------------------------------------------- world and external dependency
    P("WLD-001", "world", "Public data source unreachable or changed", 2,
      [r"URLError", r"HTTP 4\d\d", r"HTTP 5\d\d", r"getaddrinfo failed"],
      ["the news feed is not loading", "the API returned an error", "no internet"], ["gdelt", "rss", "api", "feed", "trend"],
      ["Network down or API changed"], ["Every source optional; snapshot marks missing sources; never fabricate"],
      ["Mark the source unavailable in the snapshot", "Keep the last good snapshot with its age", "Retry next cycle"], ["Snapshot lists which sources answered"], None, 0.3),
    P("WLD-002", "world", "Platform policy or public mood shifts against the lane", 4,
      [r"ban", r"regulation", r"policy change", r"backlash", r"restrict"],
      ["TikTok policy changed", "public backlash against AI content", "platform restrictions on duplicated content"], ["tiktok", "youtube", "ai content", "policy", "ban", "affiliate"],
      ["Platforms restrict duplicated or AI-labeled content; mood shifts"], ["World model watches tone and attention for the lane's topics"],
      ["Check the world snapshot for the topic", "If tone or attention moved sharply, slow output and diversify", "Disclose AI and affiliate content"], ["Decision record cites the world snapshot"], None, 0.35, "general"),
    P("WLD-003", "world", "Media tone mistaken for public opinion", 3,
      [r"tone", r"sentiment", r"public opinion"],
      ["the news tone is negative so people hate it", "treating headlines as how everyone feels"], ["opinion", "sentiment", "public", "people think"],
      ["News tone measures media framing, not what people think"], ["Always label the measure; combine tone, attention and discussion"],
      ["State what each signal measures", "Report uncertainty and sample size", "Never turn tone into a claim about all people"], ["Report lists the measure and its limits"], None, 0.5),
]
